build:
	@spm build

deploy:
	@rm -rf ../../sea-modules/anji/ship
	@mkdir  ../../sea-modules/anji/ship
	@mkdir  ../../sea-modules/anji/ship/1.0.0
	@cp     dist/*.* ../../sea-modules/anji/ship/1.0.0
	@echo
	@echo   " deploy to seajs-modules/anji/ship/1.0.0"
	@echo